
###Analysis od pdf by openAI
POST http://localhost:1800/api/analysis/6a02ece36ccc7f18d040f498
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMDJlYjFkNmNjYzdmMThkMDQwZjQ5NSIsImlhdCI6MTc3ODU3NjU2OCwiZXhwIjoxNzc5MTgxMzY4fQ.f6g1b7ozUo5_sSkbNbIqNUE-typxUE-5Ary7wEqbJIw
Content-Type: application/json

{

}