
###Analysis od pdf by openAI
POST http://localhost:1800/api/analysis/6a02ded94a57744c7da0cbfa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMDJkYjg0NmFmNjFiNTRkMGNlZmI3MSIsImlhdCI6MTc3ODU3Mjk5NywiZXhwIjoxNzc5MTc3Nzk3fQ.a3NE-9yiFueZqkalH0P3NoNRJKXAKXiEDFFbg6fNN3E
Content-Type: application/json

{

}