###register

POST http://localhost:1800/api/auth/register
Content-Type: application/json

{ 
    "username": "nakshi", 
    "email": "nakshi@gmail.com", 
    "password": "123456"
}

### login
POST http://localhost:1800/api/auth/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMDJlYjFkNmNjYzdmMThkMDQwZjQ5NSIsImlhdCI6MTc3ODU3NjE1NywiZXhwIjoxNzc5MTgwOTU3fQ.WNYSQ3HJsXYG1WPxCW2uNCa88V-fJHmyyFM0PLy2GeY
Content-Type: application/json

{ 
    "email": "nakshi@gmail.com",
    "password": "123456"
}


### get current user
GET http://localhost:1800/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMDJkYjg0NmFmNjFiNTRkMGNlZmI3MSIsImlhdCI6MTc3ODU3MjIwMCwiZXhwIjoxNzc5MTc3MDAwfQ.t0Of9_OLQGEs3tSz0KMZ04_FoAuS38yABDesjksg2xE