
### upload resumeh
POST http://localhost:1800/api/resume/upload
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMDFhNWE5M2EzZDllNzE5ZDQ1NDM2ZSIsImlhdCI6MTc3ODQ5Mjg2NiwiZXhwIjoxNzc5MDk3NjY2fQ.ON_u_gWUQWoBFZMb57g5bOtiq6RiiDp9TsD9ILRGN38
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="resume"; filename="pavithra.Resume1.pdf"
Content-Type: application/pdf

< C:\Users\DELL\Downloads\resume1 (4).pdf
------Boundary--


###get all resumes
GET  http://localhost:1800/api/resume/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZmIwY2I0NTNmMThhYzMyOTAzMmE0NiIsImlhdCI6MTc3ODEzMDY0MCwiZXhwIjoxNzc4NzM1NDQwfQ.e56YYDuJdPxdF2WKUMgef1uqsIaNWsivRHMBp2wDhz8


### get resume by id
GET http://localhost:1800/api/resume/69fc1a88b3911be4cef5a5f4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZmIwY2I0NTNmMThhYzMyOTAzMmE0NiIsImlhdCI6MTc3ODEzMDY0MCwiZXhwIjoxNzc4NzM1NDQwfQ.e56YYDuJdPxdF2WKUMgef1uqsIaNWsivRHMBp2wDhz8

